FROM node:16.15.0-slim as builder
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

FROM node:16.15.0-slim
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY package.json .
RUN npm install --production
EXPOSE 3000
CMD ["npm", "start"]